import fs from 'node:fs';
export class EventLog { constructor(){this.items=[];this.seq=0} emit(type,reason,message,object){const e={id:++this.seq,time:new Date().toISOString(),type,reason,message,object};this.items.push(e);return e} timeline(){return this.items.map(e=>`${e.time} | ${e.type.padEnd(7)} | ${e.reason} | ${e.object} | ${e.message}`).join('\n')} }
export class StateStore { constructor(file){this.file=file;this.state={nodes:[],deployments:{},services:{},pods:{}}} load(){if(this.file&&fs.existsSync(this.file)) this.state=JSON.parse(fs.readFileSync(this.file));return this.state} save(){if(this.file)fs.writeFileSync(this.file,JSON.stringify(this.state,null,2))} }
export class MiniCluster { constructor({storeFile}={}){this.store=new StateStore(storeFile);this.s=this.store.load();this.events=new EventLog();}
 addNode(name,cpu,mem,labels={}){this.s.nodes.push({name,cpu,mem,usedCpu:0,usedMem:0,labels,ready:true});this.events.emit('Normal','NodeReady',`容量 cpu=${cpu}, mem=${mem}`,name)}
 applyService(svc){this.s.services[svc.name]={...svc};this.events.emit('Normal','ServiceCreated',`selector=${JSON.stringify(svc.selector)}`,svc.name)}
 applyDeployment(d){const version=d.version||'v1';this.s.deployments[d.name]={...d,version,previous:null,status:'Stable'};this.events.emit('Normal','DeploymentCreated',`期望副本=${d.replicas}`,d.name);this.reconcile(d.name)}
 fits(n,p){return n.ready&&n.cpu-n.usedCpu>=p.cpu&&n.mem-n.usedMem>=p.mem&&Object.entries(p.nodeSelector||{}).every(([k,v])=>n.labels[k]===v)}
 schedule(p){const candidates=this.s.nodes.filter(n=>this.fits(n,p));if(!candidates.length){this.events.emit('Warning','FailedScheduling','没有满足 CPU/Mem/节点选择器的节点',p.name);return false} candidates.sort((a,b)=>((b.cpu-b.usedCpu)+(b.mem-b.usedMem)/1024)-((a.cpu-a.usedCpu)+(a.mem-a.usedMem)/1024));const n=candidates[0];n.usedCpu+=p.cpu;n.usedMem+=p.mem;p.node=n.name;p.phase='Running';this.events.emit('Normal','Scheduled',`filter 通过，score 选择 ${n.name}`,p.name);return true}
 reconcile(name){const d=this.s.deployments[name];const current=Object.values(this.s.pods).filter(p=>p.deployment===name&&p.version===d.version&&p.phase!=='Terminated');for(let i=current.length;i<d.replicas;i++){const p={name:`${name}-${d.version}-${i+1}`,deployment:name,version:d.version,labels:{app:name,version:d.version},cpu:d.cpu,mem:d.mem,nodeSelector:d.nodeSelector||{},health:'Unknown',phase:'Pending'};this.s.pods[p.name]=p;this.schedule(p);this.probe(p,false)} this.store.save()}
 probe(p,forcedFail){if(p.phase!=='Running')return false;const fail=forcedFail||p.version.includes('bad');p.health=fail?'Unhealthy':'Healthy';this.events.emit(fail?'Warning':'Normal',fail?'Unhealthy':'HealthPassed',fail?'readinessProbe 失败':'readinessProbe 成功',p.name);return !fail}
 scale(name,replicas,source='Manual'){const d=this.s.deployments[name];d.replicas=replicas;this.events.emit('Normal','Scaled',`${source} 扩缩到 ${replicas}`,name);this.reconcile(name)}
 rollingUpdate(name,newVersion){const d=this.s.deployments[name];d.previous=d.version;d.version=newVersion;d.status='Progressing';this.events.emit('Normal','RollingUpdate',`${d.previous} -> ${newVersion}`,name);for(const p of Object.values(this.s.pods).filter(p=>p.deployment===name&&p.version===d.previous)){p.phase='Terminated';const n=this.s.nodes.find(n=>n.name===p.node);n.usedCpu-=p.cpu;n.usedMem-=p.mem;this.events.emit('Normal','PodDeleted','滚动替换旧副本',p.name)}this.reconcile(name);const fresh=Object.values(this.s.pods).filter(p=>p.deployment===name&&p.version===newVersion);if(fresh.some(p=>p.health!=='Healthy'))this.rollback(name);else {d.status='Stable';this.events.emit('Normal','RolloutComplete','所有新副本健康',name)}}
 rollback(name){const d=this.s.deployments[name], bad=d.version;for(const p of Object.values(this.s.pods).filter(p=>p.deployment===name&&p.version===bad&&p.phase!=='Terminated')){p.phase='Terminated';const n=this.s.nodes.find(n=>n.name===p.node);if(n){n.usedCpu-=p.cpu;n.usedMem-=p.mem}} d.version=d.previous;d.status='RolledBack';this.events.emit('Warning','Rollback',`版本 ${bad} 健康失败，回滚到 ${d.version}`,name);this.reconcile(name)}
 hpa(name,metric,target){const d=this.s.deployments[name], desired=Math.max(d.minReplicas||1,Math.min(d.maxReplicas||10,Math.ceil(d.replicas*metric/target)));if(desired!==d.replicas)this.scale(name,desired,'HPA');this.events.emit('Normal','HPAMetric',`cpu=${metric}%, target=${target}%`,name)}
 status(){return {nodes:this.s.nodes,deployments:this.s.deployments,pods:Object.values(this.s.pods),services:this.s.services}}
}
